---
## Full Barrett Workspace
#x_lim:
#  min: -1.0
#  max: 0.3
#  step: 0.1
#
#y_lim:
#  min: -1.2
#  max: 1.2
#  step: 0.1
#
#z_lim:
#  min: -0.5
#  max: 1.2
#  step: 0.1
#
#roll_lim:
#  min: math.pi*0
#  max: math.pi
#  step: math.pi
#
#pitch_lim:
#  min: -math.pi/2.0
#  max: math.pi/2.0
#  step: math.pi/4
#
#yaws_lim:
#  min: -math.pi
#  max: math.pi
#  step: math.pi/4

## Single position
#x_lim:
#  min: -1.0
#  max: 0.3
#  step: 0.1
#
#y_lim:
#  min: 0.0
#  max: 0.1
#  step: 0.1
#
#z_lim:
#  min: 0.0
#  max: 0.1
#  step: 0.1
#
#roll_lim:
#  min: math.pi*0
#  max: math.pi
#  step: math.pi
#
#pitch_lim:
#  min: -math.pi/2.0
#  max: math.pi / 2.0
#  step: math.pi
#
#yaws_lim:
#  min: -math.pi
#  max: math.pi
#  step: math.pi

######################
# Distributed run
# Run 1
x_lim:
  min: -1.0
  max: -0.9
  step: 0.1
# Run 2
#x_lim:
#  min: -0.9
#  max: -0.8
#  step: 0.1

# Run 3
#x_lim:
#  min: -0.8
#  max: -0.7
#  step: 0.1

# Run 4
#x_lim:
#  min: -0.7
#  max: -0.6
#  step: 0.1

# Run 5
#x_lim:
#  min: -0.6
#  max: -0.5
#  step: 0.1
# Run 6
#x_lim:
#  min: -0.5
#  max: -0.4
#  step: 0.1

# Run 7
#x_lim:
#  min: -0.4
#  max: -0.3
#  step: 0.1

# Run 8
#x_lim:
#  min: -0.3
#  max: -0.2
#  step: 0.1

# Run 9
#x_lim:
#  min: -0.2
#  max: -0.1
#  step: 0.1

# Run 10
#x_lim:
#  min: -0.1
#  max: -0.0
#  step: 0.1

# Run 11
#x_lim:
#  min: -0.0
#  max: 0.1
#  step: 0.1

# Run 12
#x_lim:
#  min: 0.1
#  max: 0.2
#  step: 0.1

# Run 13
#x_lim:
#  min: 0.2
#  max: 0.3
#  step: 0.1

y_lim:
  min: -1.2
  max: 1.2
  step: 0.1

z_lim:
  min: -0.5
  max: 1.2
  step: 0.1

roll_lim:
  min: math.pi*0
  max: math.pi
  step: math.pi

pitch_lim:
  min: -math.pi/2.0
  max: math.pi/2.0
  step: math.pi/4

yaws_lim:
  min: -math.pi
  max: math.pi
  step: math.pi/4

planner_time_limit: 0.1
limits_reference_frame: 'staubli_rx60l_link1'
robot_move_group: 'StaubliArm'
end_effector_name: staubli_rx60l_link7
#NOTE this is between planning a full path or doing and ik/collions check
use_ik_only: True