---
x_min: -1.1
x_max: 0.2
x_step: 0.05

y_min: -1.3
y_max: 1.2
y_step: 0.05

z_min: -0.5
z_max: 1.1
z_step: 0.05

roll_min: -math.pi
roll_max: '0'
roll_step: math.pi/8

pitch_min: -math.pi
pitch_max: math.pi
pitch_step: math.pi/8

yaw_min: -math.pi
yaw_max: math.pi
yaw_step: math.pi/8

planner_time_limit: 0.1
limits_reference_frame: 'staubli_rx60l_link1'
robot_move_group: 'StaubliArm'
end_effector_name: staubli_rx60l_link7
graspit_link_name: approach_tran
use_ik_only: True

incomplete_task_collection_name: barrett_to_do
finished_task_collection_name: barrett_finished