---
x_lim:
  min: -0.9
  max: 0.9
  step: 0.2

y_lim:
  min: -0.9
  max: 0.9
  step: 0.2

z_lim:
  min: 0.0
  max: 1.8
  step: 0.2

roll_lim:
  min: -math.pi
  max: math.pi
  step: math.pi/4

pitch_lim:
  min: -math.pi
  max: math.pi
  step: math.pi/4

yaws_lim:
  min: -math.pi
  max: math.pi
  step: math.pi/4

planner_time_limit: 0.005
limits_reference_frame: 'base_link'
robot_move_group: 'arm'
end_effector_name: gripper_link
use_ik_only: True