---
x_lim:
  min: 0.0
  max: 1.2
  step: 0.1

y_lim:
  min: -1.1
  max: 1.1
  step: 0.1

z_lim:
  min: 0.0
  max: 2.0
  step: 0.1

roll_lim:
  min: -math.pi
  max: math.pi
  step: math.pi

pitch_lim:
  min: -math.pi
  max: math.pi
  step: math.pi/4

yaws_lim:
  min: -math.pi
  max: math.pi
  step: math.pi/4

planner_time_limit: 0.1
limits_reference_frame: 'base_link'
robot_move_group: 'arm'
end_effector_name: wrist_roll_link
use_ik_only: False