---
x_lim:
  min: -1.0
  max: 1.0
  step: 0.1

y_lim:
  min: -1.0
  max: 1.0
  step: 0.1

z_lim:
  min: 0.0
  max: 1.6
  step: 0.1

roll_lim:
  min: 0.0
  max: math.pi*2
  step: 1

pitch_lim:
  min: math.pi*-0.5
  max: math.pi*0.5
  step: 0.1

yaws_lim:
  min: 0.0
  max: math.pi*2
  step: 1

planner_time_limit: 0.5
limits_reference_frame: 'base_link'
robot_move_group: "arm"
